# Generated by Django 5.2 on 2026-03-22 08:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('business', 'Business'), ('creative', 'Creative'), ('medical', 'Medical'), ('government', 'Government')], max_length=20)),
                ('type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('yes_no', 'Yes/No')], max_length=10)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('weight', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('scores', models.JSONField(default=dict)),
                ('top_category', models.CharField(max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
            ],
            options={
                'unique_together': {('session_id', 'question')},
            },
        ),
    ]
