# Generated by Django 5.2 on 2026-03-24 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testresponse_testresult_delete_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('stream', models.CharField(blank=True, choices=[('PCM', 'Physics, Chemistry, Mathematics'), ('PCB', 'Physics, Chemistry, Biology'), ('Commerce', 'Commerce'), ('Arts', 'Arts/Humanities')], max_length=20, null=True)),
                ('current_step', models.IntegerField(default=1)),
                ('preference_boost_scores', models.JSONField(default=dict)),
                ('test_scores', models.JSONField(default=dict)),
                ('final_scores', models.JSONField(default=dict)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='trait',
        ),
        migrations.RemoveField(
            model_name='testresponse',
            name='score',
        ),
        migrations.RemoveField(
            model_name='testresponse',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='analytical_score',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='creative_score',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='investigative_score',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='practical_score',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='recommended_field',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='social_score',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('business', 'Business'), ('medical', 'Medical'), ('creative', 'Creative'), ('social', 'Social')], default='technical', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('scale', 'Scale (1-5)'), ('aptitude', 'Aptitude (Multiple Choice)'), ('preference', 'Preference Boost')], default='scale', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='testresponse',
            name='score_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='recommended_degrees',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='scores',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='secondary_domain',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='top_domain',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.question')),
            ],
        ),
        migrations.AddField(
            model_name='testresponse',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.questionoption'),
        ),
        migrations.AddField(
            model_name='testresponse',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.testsession'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='core.testsession'),
        ),
    ]
