# Generated by Django 5.2 on 2026-03-26 07:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testsession_remove_question_trait_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresponse',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='testresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='testresponse',
            name='session',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='session',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='final_scores',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='preference_boost_scores',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='test_scores',
        ),
        migrations.AddField(
            model_name='question',
            name='is_mcq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='test_type',
            field=models.CharField(choices=[('aptitude', 'Aptitude'), ('interest', 'Interest'), ('personality', 'Personality')], default='aptitude', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='trait',
            field=models.CharField(default='logical', max_length=20),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='session_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.question')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aptitude_scores', models.JSONField(default=dict)),
                ('interest_scores', models.JSONField(default=dict)),
                ('personality_scores', models.JSONField(default=dict)),
                ('top_domain', models.CharField(max_length=50)),
                ('recommended_degrees', models.JSONField(default=list)),
                ('ai_explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='core.testsession')),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.option')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.testsession')),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
        migrations.DeleteModel(
            name='TestResponse',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
