# Generated by Django 5.2 on 2026-03-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_ai_guidance'),
        ('core', '0004_remove_testresponse_selected_option_and_more'),
    ]

    operations = [
    ]
