# Generated by Django 5.2 on 2026-03-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20260326_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='ai_explanation',
        ),
    ]
