# Generated by Django 5.2 on 2026-04-18 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_testsession_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolUserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('question_text', models.TextField()),
                ('answer_text', models.CharField(max_length=50)),
                ('answer_value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_responses', to='core.testsession')),
            ],
        ),
    ]
