# Generated by Django 5.2 on 2026-04-18 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_schooluserresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_scores', models.JSONField(default=dict)),
                ('recommended_stream', models.CharField(max_length=50)),
                ('ai_guidance', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_result', to='core.testsession')),
            ],
        ),
    ]
