# Generated by Django 5.2 on 2026-04-18 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_schoolresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('step', models.IntegerField(choices=[(1, 'Step 1 - Self Awareness'), (2, 'Step 2 - Academic Interests'), (3, 'Step 3 - Career Preferences'), (4, 'Step 4 - Skills & Abilities'), (5, 'Step 5 - Values & Goals')])),
                ('trait', models.CharField(choices=[('analytical', 'Analytical Thinking'), ('biological_interest', 'Biological Interest'), ('business_interest', 'Business Interest'), ('humanities_interest', 'Humanities Interest'), ('social', 'Social Skills'), ('creative', 'Creative Thinking'), ('technical', 'Technical Aptitude'), ('leadership', 'Leadership'), ('communication', 'Communication'), ('problem_solving', 'Problem Solving')], max_length=20)),
                ('stream_hint', models.CharField(choices=[('PCM', 'Physics, Chemistry, Mathematics'), ('PCB', 'Physics, Chemistry, Biology'), ('Commerce', 'Commerce Stream'), ('Arts', 'Arts Stream'), ('General', 'All Streams')], default='General', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Question',
                'verbose_name_plural': 'School Questions',
                'ordering': ['step', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='schooluserresponse',
            name='question_id',
        ),
        migrations.AddField(
            model_name='schooluserresponse',
            name='legacy_question_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schooluserresponse',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schoolquestion'),
        ),
    ]
