# Generated by Django 5.2 on 2026-04-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_schoolquestion_remove_schooluserresponse_question_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolquestion',
            options={},
        ),
        migrations.RemoveField(
            model_name='schoolquestion',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='schoolquestion',
            name='step',
        ),
        migrations.RemoveField(
            model_name='schoolquestion',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='schooluserresponse',
            name='question',
        ),
        migrations.AlterField(
            model_name='schoolquestion',
            name='stream_hint',
            field=models.CharField(choices=[('PCM', 'Physics, Chemistry, Mathematics'), ('PCB', 'Physics, Chemistry, Biology'), ('Commerce', 'Commerce'), ('Arts', 'Arts'), ('General', 'General')], max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolquestion',
            name='trait',
            field=models.CharField(choices=[('analytical', 'Analytical'), ('biological_interest', 'Biological Interest'), ('business_interest', 'Business Interest'), ('humanities_interest', 'Humanities Interest'), ('social', 'Social')], max_length=30),
        ),
        migrations.AlterField(
            model_name='schooluserresponse',
            name='answer_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='schooluserresponse',
            name='answer_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schooluserresponse',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
