# Generated by Django 5.2 on 2026-04-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_schoolmcqquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolresult',
            name='mcq_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='schoolresult',
            name='mcq_score',
            field=models.IntegerField(default=0),
        ),
    ]
