# Generated by Django 5.2 on 2026-04-18 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_schoolresult_mcq_percentage_schoolresult_mcq_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolmcqresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='schoolmcqresponse',
            name='session',
        ),
        migrations.RemoveField(
            model_name='schoolquestion',
            name='trait',
        ),
        migrations.RemoveField(
            model_name='schooluserresponse',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='schooluserresponse',
            name='answer_value',
        ),
        migrations.RemoveField(
            model_name='schooluserresponse',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='schooluserresponse',
            name='question_text',
        ),
        migrations.AddField(
            model_name='schoolquestion',
            name='correct_answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='schoolquestion',
            name='option_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolquestion',
            name='option_b',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolquestion',
            name='option_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolquestion',
            name='option_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolquestion',
            name='step',
            field=models.IntegerField(blank=True, choices=[(1, 'Step 1'), (2, 'Step 2'), (3, 'Step 3'), (4, 'Step 4'), (5, 'Step 5')], null=True),
        ),
        migrations.AddField(
            model_name='schooluserresponse',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schooluserresponse',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schoolquestion'),
        ),
        migrations.AddField(
            model_name='schooluserresponse',
            name='selected_answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='SchoolMCQQuestion',
        ),
        migrations.DeleteModel(
            name='SchoolMCQResponse',
        ),
    ]
