# Generated by Django 5.2 on 2026-04-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_schoolmcqresponse_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolquestion',
            name='stream_hint',
            field=models.CharField(choices=[('PCM', 'Physics, Chemistry, Mathematics'), ('PCB', 'Physics, Chemistry, Biology'), ('Commerce', 'Commerce'), ('Arts', 'Arts')], max_length=20),
        ),
    ]
